### PR TITLE
[#89] Add SSE Send Timeout

### PR DESCRIPTION
**Pull request by blodow**
As described in #89, this adds a `send_timeout` parameter to the `EventSourceResponse` initializer. In the event of the `send` call inside the response's sending logic exceeding this duration, a `SendTimeoutError` is raised, aborting the SSE event generator and effectively canceling the HTTP connection.

### CODE REVIEW

**Comment by sysid** [comment]
@blodow, thank you for this PR, much appreciated! Please give me some time to review it properly.

**Comment by sysid** [comment]
@blodow , following feedback
1. Your use-case is valid and your PR as well.
2. `make test` was not working, which I fixed.

After upgrade dependecies:
1. tests via `make tox` are breaking for python 12: `anyio` has got breaking changes: `ExceptionGroups`

At this point I need to stop due to time constraints. However, `make tox` needs to pass in order to get the PR merged.
Maybe you can have a look at it.

**Comment by blodow** [comment]
@sysid I think I managed to fix the remaining issues in a sort of minimally-invasive way. Let me know if you would like to see any other changes.

**Review by sysid — APPROVED** [review]
Nice!

**Pull request merged**
